### ISSUE TITLE
P0 - Reorder CI workflow

### ISSUE THREAD

**Issue by geleeroyale** [GeneralMagicio/unicorn-backend#13]
@GeneralMagicio/devops 

This does not only concern this repo, but many many more where we use CI to connect to a VPS to build and deploy containerized software.

We might want to change the order of commands in the workflow as we should try to **build before shutting down** the old container.
 
<img width="245" alt="image" src="https://github.com/user-attachments/assets/8a54f7bf-fe4d-45c0-8842-fe62601abf0d">

@mhmdksh is working on something - maybe he can give more details

**Comment by mhmdksh** [comment]
@geleeroyale  This has been done and can be closed
